### ISSUE TITLE
Tutorial IoT-over-MQTT broken

### ISSUE THREAD

**Issue by olisom** [FIWARE/tutorials.NGSI-v2#12]
Hello,

1/Provisioning the Smart Lamp request (10) returns : 
```
    "name": "DUPLICATE_DEVICE_ID",
    "message": "A device with the same pair (Service, DeviceId) was found:lamp001"
```
as the lamp already exists with : 
```
            "device_id": "lamp001",
            "entity_name": "Thing:lamp001",
            "entity_type": "Thing",
```
2/Opening the Smart Door request(13) returns : 
```
    "error": "NotFound",
    "description": "The requested entity has not been found. Check type and id"
```
In the http://localhost:3000/device/monitor page sending the command open to the door001 does not work either.

3/Switching ON the Smart Lamp request(14) returns : 
```
    "error": "NotFound",
    "description": "The requested entity has not been found. Check type and id"
```
On page http://localhost:3000/device/monitor, sending the switch ON command to lamp001 does not work either.

4/ Some queries are provided in Postman in 'Enabling Context Broker Commands' to register device commands, but it's not clear whether these queries should be used or not (as they don't appear in the tutorial).

**Comment by jason-fox** [comment]
Actually this is just a timing issue. In order for the graphs in the time-series and short-term history tutorials to look nice, it is necessary for the dummy devices to send out periodic `0` values when the lamp is switched off. If you get an unknown device (`lamp001`) pushing data to MQTT  the IoT Agent will create an Entity for you. What has happened is that the Bell has been rung, which sets the other devices to start sending data, and the lamp has send data before being properly provisioned.

You can check this using:

```console
curl -X GET \ 
  'http://localhost:1026/v2/entities/Thing:lamp001' \                         
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /'  
```

An if necessary, you can DELETE the entity like this:

```console
curl -X DELETE \ 
  'http://localhost:1026/v2/entities/Thing:lamp001' \                         
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /'  

curl -iX DELETE \ 
  'http://localhost:4041/iot/devices/lamp001'   -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /'    
```

Then the command will succeed.
