### ISSUE TITLE
Update broken link

### ISSUE THREAD

**Issue by rusty3699** [FIWARE/tutorials.NGSI-v2#6]
Please update this broken github's repo link STOCK MANAGEMENT EXAMPLE

link for Ref :- https://fiware-tutorials.readthedocs.io/en/latest/accessing-context.html
Github's link for ref - https://github.com/FIWARE/tutorials.Step-by-Step/tree/master/context-provider

**Comment by jason-fox** [comment]
I think this is fixed via f2b6ed136 - can you confirm?

**Comment by rusty3699** [comment]
Hey! Not able to access it still.

**Comment by jason-fox** [comment]
That's odd - it seems to be OK for me. The ReadTheDocs documentation is generated. Could you refresh your cache and try again to get the latest version of _"latest"_. Then, assuming it still doesn't work could you attach a screenshot containing the relevant link on screen - maybe I'm testing the wrong bit of text.
